package vn.techres.line.helper;

public enum TechresStatusRequestEnum {
     SUCCESS_CODE {
        @Override
        public String toString() {
            return "200";
        }
    }


}
//REPORT_REVENUE_WEEK","PROMOTION_MANAGER","REPORT_FOOD_IN_DAY","REPORT_ORDER","REPORT_REVENUE_DAY","REPORT_DRINK_YEAR","FOOD_MANAGER","TASK_MANAGER","DISCOUNT_FOOD","REPORT_FOOD_WEEK","REPORT_MANAGER","CANCEL_DRINK","REPORT_FOOD_MONTH","REPORT_REVENUE_ALL","REPORT_FOOD_ALL","EMPLOYEE_LEAVE_FORM_MANAGER","ORDERS_MANAGER","REPORT_REVENUE","SALARY_LEVEL_MANAGER","REPORT_FOOD_DAY","NEWS_MANAGER","BOOKING_MANAGER","ORDER_SESSION_MANAGER","EMPLOYEE_KAIZEN_MANAGER","REPORT_WAREHOUSE_IN_DAY","WORKING_SESSION_MANAGER","REPORT_DRINK_DAY","REPORT_DRINK_WEEK","EMPLOYEE_MANAGER","REPORT_DRINK_ALL","CUSTOMER_MANAGER","REPORT_FOOD_YEAR","REPORT_REVENUE_YEAR","REPORT_WAREHOUSE_YEAR","REPORT_DRINK_MONTH","CHECKIN_MANAGER","REPORT_FOOD","REPORT_WAREHOUSE_DAY","ADD_CUSTOM_FOOD","REPORT_WAREHOUSE_ALL","GIFT_FOOD","REPORT_VAT","REPORT_DRINK","JOB_MANAGER","BANNER_MANAGER","CANCEL_COMPLETED_FOOD","REPORT_GIFT_FOOD","REPORT_WAREHOUSE_WEEK","SALARY_MANAGER","SALARY_TARGET_MANAGER","EMPLOYEE_RANKING_MANAGER","REPORT_DISCOUNT","REPORT_DRINK_IN_DAY","DISCOUNT_ORDER","AREA_TABLE_MANAGER","ORDER_FOOD","RANK_MANAGER","REPORT_REVENUE_IN_DAY","REPORT_WAREHOUSE_MONTH","BRANCH_MANAGER","REPORT_REVENUE_MONTH